[versions]
assertJ = "3.25.3"
junit-bom = "5.10.2"
org-apache-commons-commons-compress = "1.26.1"
org-tukaani-xz = "1.9"
spotless = "6.25.0"

[libraries]
org-apache-commons-commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "org-apache-commons-commons-compress" }
org-tukaani-xz = { module = "org.tukaani:xz", version.ref = "org-tukaani-xz" }

# TEST dependencies
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertJ" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
